import type { DMMF } from "@prisma/generator-helper";

type EnumList = readonly DMMF.DatamodelEnum[];

export function generateJsEnums(enums: EnumList): string {
  const lines: string[] = [
    "// Generated by prisma-generator-js-enums — do not edit manually",
    "",
  ];

  for (const enumDef of enums) {
    const values = enumDef.values.map((v) => v.name);
    lines.push(`const ${enumDef.name} = Object.freeze({`);
    for (const value of values) {
      lines.push(`  ${value}: "${value}",`);
    }
    lines.push("});", "");
  }

  const names = enums.map((e) => e.name);
  if (names.length > 0) {
    lines.push(`module.exports = { ${names.join(", ")} };`, "");
  } else {
    lines.push("module.exports = {};", "");
  }

  return lines.join("\n");
}

export function generateTsEnums(enums: EnumList): string {
  const lines: string[] = [
    "// Generated by prisma-generator-js-enums — do not edit manually",
    "",
  ];

  for (const enumDef of enums) {
    const values = enumDef.values.map((v) => v.name);
    lines.push(`export const ${enumDef.name} = {`);
    for (const value of values) {
      lines.push(`  ${value}: "${value}",`);
    }
    lines.push("} as const;", "");
    lines.push(
      `export type ${enumDef.name} = (typeof ${enumDef.name})[keyof typeof ${enumDef.name}];`,
      ""
    );
  }

  return lines.join("\n");
}
